name: Test On Push
on: push
jobs:
  run_test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS Env
        uses: actions/setup-node@v2-beta
      - name: Install Deps
        run: npm i
      - name: Run Tests
        run: npm t
